# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160315_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='affiliate_sku',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='affiliate_url',
            field=models.URLField(default='www.amazon.com'),
            preserve_default=False,
        ),
    ]
